sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  global:
   - TEST_APPS="allauth account socialaccount amazon angellist bitbucket coinbase evernote feedly foursquare douban dropbox dropbox_oauth2 facebook flickr google github hubic instagram linkedin linkedin_oauth2 mailru odnoklassniki windowslive openid orcid paypal persona soundcloud spotify stackexchange tumblr twitch twitter vimeo vk weibo bitly xing"
  matrix:
   - DJANGO=Django==1.5
   - DJANGO=Django==1.6
   - DJANGO=Django==1.7
   - DJANGO=Django==1.8
install:
 - pip install $DJANGO --use-mirrors
 - pip install . --use-mirrors
 - pip install coverage

script: coverage run manage.py test animals

after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls