language: python
install:
  - pip install tox 
script:
  - tox

after_success:
  - coverage report
  - pip install -q python-coveralls
  - coveralls

env:
  - TOXENV=django15
  - TOXENV=django16
  - TOXENV=django17