language: python
install:
  - pip install tox 
script:
  - tox

after_success:
  - coverage report
  - pip install -q python-coveralls
  - coveralls

env:
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=flake8